
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/Dockerfile to edit this template

FROM amazoncorretto:11-alpine-jdk

COPY SpringBoot-0.0.1-SNAPSHOT.jar APIBackend.jar

ENTRYPOINT ["java","-jar","/APIBackend.jar"]